version: '3.4'

services:
  api:
    image: api
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - ~/.vsdbg:/remote_debugger

  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "Teste"
        ACCEPT_EULA: "Y"