version: '3.1'

services:
  api:
    container_name: "teste-sage-api"
    image: 'teste-sage-api'
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/backend
    ports:
      - "5000:80"
    depends_on:
      - "database"
    networks:
      - sagetest-network
  web:
    container_name: "teste-sage-web"
    image: 'teste-sage-web'
    build: 
      context: ./frontend_react
      dockerfile: Dockerfile
    ports:
      - "3000:3000" 
    depends_on:
      - "api"
    networks:
      - sagetest-network
  database:
    container_name: "sql-server"
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Teste@123"
      ACCEPT_EULA: "Y"
    ports: 
      - "1433:1433"
    networks:
      - sagetest-network
networks:
  sagetest-network:
    driver: bridge