version: '3.4'

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000
      - 5001
    depends_on:
      - db
  web:
    build: 
      context: ./frontend_react
      dockerfile: Dockerfile
    ports:
      - 3000
    depends_on:
      - api
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Teste@123"
      ACCEPT_EULA: "Y"