version: '3.4'

services:
  api:
    build:
      context: .
      dockerfile: backend/Api/Dockerfile
    ports:
      - 5000
      - 5001
    depends_on:
      - db
  web:
    build: 
      context: .
      dockerfile: frontend_react/Dockerfile
    ports:
      - 3000
    depends_on:
      - api
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Teste@123"
      ACCEPT_EULA: "Y"